name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-build:
    name: Lint and Build Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint || (echo "Linting failed. Please fix the issues above." && exit 1)

      - name: Type check
        run: npm run typecheck || (echo "Type checking failed. Please fix the type errors above." && exit 1)

      - name: Build check
        run: npm run build || (echo "Build failed. Please check the errors above." && exit 1)
